services:
  - type: web
    name: nobu-fastapi-price
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn fastapi_price_server:app --host 0.0.0.0 --port 8000"
